spring:
  application:
    name: graphql-postgres-api

  config:
    import: "file:../db-credentials.yml"

  datasource:
    url: jdbc:postgresql://dontpanic.k42.app:5432/galaxy
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true

  graphql:
    http:
      path: /graphql

